version: '3.4'

networks:
  sonarnet:
    external: true
    name: sonarnet

services:
    sonarqube:
        image: sonarqube:7.9.1-community
        environment:
            - sonar.jdbc.username=sonar
            - sonar.jdbc.password=sonar
            - sonar.jdbc.url=jdbc:postgresql://db-postgresql/sonarqube
        ports:
            - 9000:9000
            - 9092:9092
        networks:
            - sonarnet
        volumes:   
            - ./extensions:/opt/sonarqube/extensions
            - ./logs:/opt/sonarqube/logs
            - ./data:/opt/sonarqube/data

    db-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/user1/app-postgresql/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=sonarqube
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        ports:
            - 5432:5432
        networks:
            - sonarnet